# Generated by Django 3.2.9 on 2021-12-13 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('costNote', models.TextField()),
                ('deliveryCost', models.IntegerField()),
                ('arrivesWithinMin', models.DurationField()),
                ('arrivesWithinMax', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField()),
                ('isActive', models.BooleanField()),
                ('isPaid', models.BooleanField()),
                ('comment', models.TextField()),
                ('recipientName', models.CharField(max_length=300)),
                ('recipientPhoneNumber', models.CharField(max_length=20)),
                ('recipientEmailAddress', models.EmailField(max_length=254)),
                ('deliveryAddress', models.CharField(max_length=2000)),
                ('deliveryMethod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cart.deliverymethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chessboard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
    ]
