# Generated by Django 3.2.9 on 2021-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='deliveryType',
            field=models.SmallIntegerField(choices=[(1, 'Pickup location'), (2, 'Address')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryCompany',
            field=models.CharField(default='компания', max_length=200),
            preserve_default=False,
        ),
    ]
