# Generated by Django 3.2.9 on 2021-12-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orderitem_optionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='optionName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
