# Generated by Django 3.2.9 on 2021-12-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_orderitem_optionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='arrivesWithinMax',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='arrivesWithinMin',
            field=models.IntegerField(default=1),
        ),
    ]
