# Generated by Django 3.2.9 on 2021-12-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20211227_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='arrivesWithinMax',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='arrivesWithinMin',
            field=models.DurationField(null=True),
        ),
    ]
