# Generated by Django 3.2.9 on 2021-12-26 21:41

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=1000)),
                ('photo', models.ImageField(default='default_profile_picture.jpg', upload_to=employees.models.get_employee_photo_upload_path)),
            ],
        ),
    ]
