# Generated by Django 3.2.9 on 2021-12-26 13:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboard',
            name='image',
            field=models.ImageField(null=True, upload_to=products.models.get_chessboard_image_upload_path),
        ),
    ]
