# Generated by Django 3.2.9 on 2021-12-26 14:26

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_chessboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboard',
            name='image',
            field=models.ImageField(default='default_board_image.png', upload_to=products.models.get_chessboard_image_upload_path),
        ),
    ]
