# Generated by Django 3.2.9 on 2021-12-26 20:38

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_chessboard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessboard',
            name='image',
        ),
        migrations.AddField(
            model_name='chessboard',
            name='driveType',
            field=models.CharField(default='abcd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chessboard',
            name='powerW',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chessboard',
            name='weightKg',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChessboardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_board_image.png', upload_to=products.models.get_chessboard_image_upload_path)),
                ('chessboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.chessboard')),
            ],
        ),
    ]
