# Generated by Django 3.2.9 on 2021-12-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211226_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboard',
            name='description',
            field=models.TextField(default='описание'),
        ),
        migrations.AlterField(
            model_name='chessboard',
            name='heightCm',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='chessboard',
            name='itemName',
            field=models.CharField(default='Доска', max_length=1000),
        ),
        migrations.AlterField(
            model_name='chessboard',
            name='lengthCm',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='chessboard',
            name='price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='chessboard',
            name='widthCm',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='chessboardoption',
            name='name',
            field=models.CharField(default='вариация', max_length=100),
        ),
    ]
