# Generated by Django 3.2.9 on 2021-12-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profilePicture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.image')),
            ],
        ),
    ]
