# Generated by Django 3.2.9 on 2021-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profilePicture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
