# Generated by Django 3.2.9 on 2021-12-26 12:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211226_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profilePicture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to=users.models.get_profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
